model:
  type: Pi0Config
  max_token_len: 200
  pi05: true
  discrete_state_input: true
  enable_training_time_rtc: true
weight_loader:
  type: CheckpointWeightLoader
  params_path: gs://openpi-assets/checkpoints/pi05_base/params
ema_decay: null
data:
  type: LeRobotBiFlexivDataConfig
  repo_id: Xense/loreal_returns_sorting_0717
  base_config:
    prompt_from_task: true
  default_prompt: Pick up the returned cosmetic product, scan its barcode, and place it into the return cart.
batch_size: 16
num_workers: 8
num_train_steps: 40000
fsdp_devices: 1
checkpoint_base_dir: /root/autodl-fs/shilin